// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwzumySZsIlJ1IYsP0tgOUTRMlz1BUuhs',
    appId: '1:224978934284:ios:1b8dc08d8d9823dec1ec29',
    messagingSenderId: '224978934284',
    projectId: 'agrovani-104f8',
    storageBucket: 'agrovani-104f8.firebasestorage.app',
    iosBundleId: 'com.example.agrovani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwzumySZsIlJ1IYsP0tgOUTRMlz1BUuhs',
    appId: '1:224978934284:ios:1b8dc08d8d9823dec1ec29',
    messagingSenderId: '224978934284',
    projectId: 'agrovani-104f8',
    storageBucket: 'agrovani-104f8.firebasestorage.app',
    iosBundleId: 'com.example.agrovani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByQ77yPZ-qG9vjZ6dsSczXl79p3wOmY5Q',
    appId: '1:224978934284:web:84ea01159b4d7ba1c1ec29',
    messagingSenderId: '224978934284',
    projectId: 'agrovani-104f8',
    authDomain: 'agrovani-104f8.firebaseapp.com',
    storageBucket: 'agrovani-104f8.firebasestorage.app',
    measurementId: 'G-EHMDT9JQGB',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQ77yPZ-qG9vjZ6dsSczXl79p3wOmY5Q',
    appId: '1:224978934284:web:84ea01159b4d7ba1c1ec29',
    messagingSenderId: '224978934284',
    projectId: 'agrovani-104f8',
    authDomain: 'agrovani-104f8.firebaseapp.com',
    storageBucket: 'agrovani-104f8.firebasestorage.app',
    measurementId: 'G-EHMDT9JQGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmTu5_ZZz8psh3J_7Pz28q7xHeCnlSKP4',
    appId: '1:224978934284:android:00683c9e0ead7dd6c1ec29',
    messagingSenderId: '224978934284',
    projectId: 'agrovani-104f8',
    storageBucket: 'agrovani-104f8.firebasestorage.app',
  );

}
